sudo: false
language: node_js
node_js:
  - 10
  - 8
  - 6
  cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - npm install codecov -g
  - yarn run test
after_success:
  - codecov
