sudo: false
language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - npm install codecov -g
  - npm install bundlesize -g
  - yarn test
  - yarn build
  - yarn filesize
after_success:
  - codecov
